version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-without-venv
    volumes:
      - .:/app
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      TARGET_CHANNEL_NAME: ${TARGET_CHANNEL_NAME}
      CRON_USER: ${CRON_USER}
    ports:
      - "1330:3000"
