FROM python:3.9-slim-buster

RUN apt-get update && \
    apt-get install -y vim cron tzdata && \
    rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Dhaka

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY crontab /etc/cron.d/crontab

RUN chmod 0644 /etc/cron.d/crontab

RUN crontab /etc/cron.d/crontab

CMD ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && service cron start && python main.py
